# # BEGIN_KITTY_FONTS
# font_family      family="MonoLisa"
# bold_font        auto
# italic_font      auto

# # END_KITTY_FONTS


# Mimic alacritty font weights
text_composition_strategy legacy

confirm_os_window_close 0


# Remote control
allow_remote_control yes
# For opacity sockets
# listen_on unix:/tmp/opkitty
# For kitty scrollback_pager
listen_on unix:/tmp/kitty

# Shell
shell zsh


# Remove scrollback_pager & layout stack
map ctrl+shift+h no_op
map ctrl+shift+l no_op

# kitty_mod ctrl+alt
kitty_mod ctrl+shift

shell_integration enabled
# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '/home/mar/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

# Copy the pure text output of the last command directly to the clipboard
map ctrl+shift+y launch --stdin-source=@last_cmd_output --type=clipboard

# Font Configuration
font_family      family="CaskaydiaCove Nerd Font"
# font_family      family="MonoLisa"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Window Layout & Padding
dynamic_background_opacity yes
window_padding_width 5 10
background_opacity 1.0

# Clipboard Behavior
copy_on_select yes

# Press Ctrl+Shift+H to open the current buffer in Neovim
# scrollback_pager lvim -c "set nonumber nolist" -c "silent! %s/\%u1b\[[0-9;]*m//g" -c "normal G" -

# cursor options
shell_integration no-cursor
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_blink_interval 0
cursor_shape block
# cursor #5af78e
# cursor #A4E400
cursor #a6e3a1
# cursor_trail_color #ff5c57 
cursor_trail_color #57c7ff 

# Inferred Primary Colors
background #262626
foreground #f1f1f0

active_border_color #ff5c57
inactive_border_color #585b70

# Normal Colors
color0  #282a36
color1  #ff5c57
# color2  #5af78e
color2 #a6e3a1
color3  #f3f99d
color4  #57c7ff
color5  #ff6ac1
color6  #9aedfe
color7  #f1f1f0

# Bright Colors
color8  #686868
color9  #ff5c57
color10 #5af78e
color11 #f3f99d
color12 #57c7ff
color13 #ff6ac1
color14 #9aedfe
color15 #f1f1f0
