# Legacy Yazi File Chooser Rules (For Fedora)
windowrulev2 = float,class:^(yazi-picker)$
windowrulev2 = center,class:^(yazi-picker)$
windowrulev2 = stayfocused,class:^(yazi-picker)$
windowrulev2 = dimaround,class:^(yazi-picker)$
windowrulev2 = size 1100 650,class:^(yazi-picker)$


# Force zotero settings to render floating well
windowrulev2 = float, class:^(Zotero)$, title:^(Zotero Settings)$
windowrulev2 = center, class:^(Zotero)$, title:^(Zotero Settings)$
windowrulev2 = size 800 600, class:^(Zotero)$, title:^(Zotero Settings)$
