plugin {
    easymotion {
        textfont = MonoLisa-Black
        textsize = 25
        textcolor = rgba(000000ff)
        bgcolor = rgba(f66151ff)
        # Vertical padding is usually smaller than horizontal to compensate 
        # for the rectangular nature of most font glyphs.
        textpadding = 8 15 8 15
        bordersize = 2
        bordercolor = rgba(f66151ff)
        rounding = 10
        motionkeys = hjklgnmyuiopsb
        motionlabels = HJKLGNMYUIOPSB
        fullscreen_action = none
    }
}
