## SUPER key
$mainMod = SUPER --- AGS Binary Modifier Tracking ---

# Run script to stop the shell binds from capturing mod keys on bottles
exec-once = ~/.scripts/bottles-mod-fix.sh


bind = SUPER CTRL, o, exec, kitty zsh -ic "fetch-obsidianconfig" # Fetch obsidian config

# Actions
bind = $mainMod, I, exec, ~/.scripts/gemini-rofi.sh

# Toggle the AGS HUD
bind = SUPER , A, exec, ags -t visual-keyboard

# SHIFT
bindin = , Shift_L, exec, echo '1' > /tmp/ags-mod-shift
bindrti = , Shift_L, exec, echo '0' > /tmp/ags-mod-shift
# CONTROL
bindin = , Control_L, exec, echo '1' > /tmp/ags-mod-ctrl
bindrti = , Control_L, exec, echo '0' > /tmp/ags-mod-ctrl
# ALT
bindin = , Alt_L, exec, echo '1' > /tmp/ags-mod-alt
bindrti = , Alt_L, exec, echo '0' > /tmp/ags-mod-alt
# SUPER / WIN
bindin = , Super_L, exec, echo '1' > /tmp/ags-mod-super
bindrti = , Super_L, exec, echo '0' > /tmp/ags-mod-super

# --- AGS CHORD TRACKING (Intercepted from Kanata) ---

# SPACE (F13)
bindin = , XF86Tools, exec, echo 'space' > /tmp/ags-active-chord
bindrtir = , XF86Tools, exec, echo 'none' > /tmp/ags-active-chord

# Z (F14)
bindin = , XF86Launch5, exec, echo 'z' > /tmp/ags-active-chord
bindrtir = , XF86Launch5, exec, echo 'none' > /tmp/ags-active-chord

# S (F15)
bindin = , XF86Launch6, exec, echo 's' > /tmp/ags-active-chord
bindrtir = , XF86Launch6, exec, echo 'none' > /tmp/ags-active-chord

# G (F16)
bindin = , XF86Launch7, exec, echo 'g' > /tmp/ags-active-chord
bindrtir = , XF86Launch7, exec, echo 'none' > /tmp/ags-active-chord

# V (F17)
bindin = , XF86Launch8, exec, echo 'v' > /tmp/ags-active-chord
bindrtir = , XF86Launch8, exec, echo 'none' > /tmp/ags-active-chord

# --- Shortcut replacements on specific windows --- Better than a whole new kanata layer

bind = CTRL, q, exec, sh -c 'hyprctl activewindow -j | grep -iq "\"class\": \"firefox\"" && hyprctl dispatch sendshortcut CTRL, w, activewindow || hyprctl dispatch sendshortcut CTRL, q, activewindow'
