# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = ~/.config/hypr/wallpapers/wallpaperflat.png
wallpaper = ,~/.config/hypr/wallpapers/wallpaperflat.png
splash = false
ipc = off
