# yazi file chooser modal rules
windowrule {
      name = yazi-picker-rules
      match:class = ^(yazi-picker)$
      float = true
      center = true
      stay_focused = true
      dim_around = true
      size = 1500 800
  }

# GPG Password Prompt Rules
windowrule {
    name = gpg-pinentry-rules
    match:class = ^(pinentry.*)$
    float = true
    center = true
    pin = true
    stay_focused = true
    dim_around = true
    # Setting a fixed size ensures it doesn't tile weirdly or appear too small
    size = 400 200 
}


windowrule {
    name = vault-auth-popup
    match:class = ^(vault-pass)$
    float = true
    center = true
    size = 400 200
    stay_focused = true
    dim_around = true
    focus_on_activate = true
}

windowrule {
    name = Zotero Settings
    match:class = ^(Zotero)$
    match:title = ^(Zotero Settings)$
    float = true
    center = true
    size = 800 600
    focus_on_activate = true
}
