# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Quick accent
  - trigger: "|oo"
    replace: "ö"
  - trigger: "|uu"
    replace: "ü"
  - trigger: "|nn"
    replace: "ñ"
  - trigger: "|aa"
    replace: "ä"
  - trigger: "|sec"
    replace: "§"

  # ==========================================
  # GPG Secret expander
  # keys are named espanso/key in the pass store
  # ==========================================
  - regex: |
      (?x)
      \| (?P<vault_key>
        id | ad1 | add | ig | bd | bic | bo | iban |
        m0 | m1  | m2  | m3 | m4 | mk  | mm |
        n1 | n2  | nm  | np |
        t1 | t2  | ww  |
        bancolombia
      )
    replace: "{{output}}"
    # For security, but it's not necessary since these are non sensitive secrets
    # force_mode: keys
    vars:
      - name: output
        type: shell
        params:
          cmd: "pass show espanso/$ESPANSO_VAULT_KEY"
          trim: true

  # ==========================================
  # Non secrets
  # ==========================================
  - trigger: "|khmm"
    replace: "Kunsthochschule für Medien Köln"
  - trigger: "|khmid"
    replace: "102475"
  - trigger: "|daad"
    replace: "91870705"

  # Print the current date
  - trigger: "|dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          # This is for german format date
          format: "%d.%m.%g"

  - trigger: "|ID"
    replace: "🆔 {{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "uuidgen | cut -d'-' -f1"

  # NOTE: We define cursor pos with $|$
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # We use > to allow "" and - to forbid newline at the end
  # - trigger: ":a"
  #   replace: >-
  #           asap $ s "$|$"
  #   force_clipboard : true

  # - regex: "t(?P<var>.*)\\|"
  #   replace: >-
  #           d{{var}} $ "
  # But matches can also be dynamic:
  #
  # We use dynamic regex, and end with . here (it could be anything)
  # - regex: "greet(?P<person>.*)\\."
  #   replace: "Hi {{person}}!"
