let
  # Your personal public keys (from termux, fedora, etc.)
  users = [
  ];

  # The system-level public keys generated by NixOS during installation
  # Obtain these by running `cat /etc/ssh/ssh_host_ed25519_key.pub

  systems = [
  ];
in
{
}
