let
  # Your personal public keys (from termux, fedora, etc.)
  users = [
  ];

  # The system-level public keys generated by NixOS during installation
  # Obtain these by running `cat /etc/ssh/ssh_host_ed25519_key.pub

  systems = [
  ];
in
{
  # Define which keys can decrypt which files.
  # Both you (the user) and the target machine must be included.
  # "cloudflare-api-token.age".publicKeys = [
  # ];
  # "obsidian-vault-password.age".publicKeys = users ++ systems;
}
